# Generated by Django 4.2.7 on 2023-12-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
