# Generated by Django 4.2.7 on 2023-12-01 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loyaltySystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diamondguest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='diamondguest',
            name='last_checkin_date',
        ),
        migrations.RemoveField(
            model_name='diamondguest',
            name='membership_tier',
        ),
        migrations.RemoveField(
            model_name='diamondguest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='diamondguest',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='diamondguest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='goldguest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='goldguest',
            name='last_checkin_date',
        ),
        migrations.RemoveField(
            model_name='goldguest',
            name='membership_tier',
        ),
        migrations.RemoveField(
            model_name='goldguest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='goldguest',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='goldguest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='silverguest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='silverguest',
            name='last_checkin_date',
        ),
        migrations.RemoveField(
            model_name='silverguest',
            name='membership_tier',
        ),
        migrations.RemoveField(
            model_name='silverguest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='silverguest',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='silverguest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='standardguest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='standardguest',
            name='last_checkin_date',
        ),
        migrations.RemoveField(
            model_name='standardguest',
            name='membership_tier',
        ),
        migrations.RemoveField(
            model_name='standardguest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='standardguest',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='standardguest',
            name='user',
        ),
        migrations.CreateModel(
            name='LoyaltySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_points', models.IntegerField(default=0)),
                ('membership_tier', models.CharField(default='Standard', max_length=50)),
                ('last_checkin_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='diamondguest',
            name='loyaltysystem_ptr',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loyaltySystem.loyaltysystem'),
        ),
        migrations.AddField(
            model_name='goldguest',
            name='loyaltysystem_ptr',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loyaltySystem.loyaltysystem'),
        ),
        migrations.AddField(
            model_name='silverguest',
            name='loyaltysystem_ptr',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loyaltySystem.loyaltysystem'),
        ),
        migrations.AddField(
            model_name='standardguest',
            name='loyaltysystem_ptr',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loyaltySystem.loyaltysystem'),
        ),
    ]
