# Generated by Django 4.2.7 on 2023-12-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('number_of_rooms', models.PositiveIntegerField()),
                ('rooms', models.ManyToManyField(to='hotel.room')),
            ],
        ),
    ]
