# Generated by Django 4.2.7 on 2023-12-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_room_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('CHECKED_IN', 'CHECKED_IN'), ('CHECKED_OUT', 'CHECKED_OUT'), ('CLEANED', 'CLEANED')], default='CLEANED', max_length=20),
        ),
    ]
