# Generated by Django 4.2.7 on 2023-11-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='status',
            new_name='room_status',
        ),
    ]
