# Generated by Django 4.2.6 on 2023-11-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_nights',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
