# Generated by Django 4.2.7 on 2023-12-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_room_delete_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
    ]
