# Generated by Django 4.2.7 on 2023-12-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_points_earned"),
        ("bookings", "0004_booking_payment_status"),
    ]

    operations = []
