# Generated by Django 4.2.7 on 2023-12-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_merge_20231202_1733"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Failed", "Failed"),
                    ("Refunded", "Refunded"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
